"""Add NCIs on task logs

Revision ID: c5f6cb8b3ad0
Revises: 97f6680166b8
Create Date: 2023-08-07 15:38:54.719282

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = 'c5f6cb8b3ad0'
down_revision = '97f6680166b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_log_task_run_id'), 'task_log', ['task_run_id'], unique=False)
    op.create_index(op.f('ix_task_log_timestamp_utc'), 'task_log', ['timestamp_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_log_timestamp_utc'), table_name='task_log')
    op.drop_index(op.f('ix_task_log_task_run_id'), table_name='task_log')
    # ### end Alembic commands ###
