"""Add soft delete to task_definition

Revision ID: da93eceb984d
Revises: ac43363c9fdd
Create Date: 2023-08-01 16:36:54.385254

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = 'da93eceb984d'
down_revision = 'ac43363c9fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_definition', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_definition', 'deleted_at')
    # ### end Alembic commands ###
