"""Align SQL models with Pydantic task prep

Revision ID: 19a3279afd31
Revises: d6f77351f497
Create Date: 2024-03-02 00:14:15.057330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.types

# revision identifiers, used by Alembic.
revision = '19a3279afd31'
down_revision = 'd6f77351f497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_run', 'start_time')
    op.add_column('task_prep_prompt', sa.Column('messages', sa.JSON(), nullable=False))
    op.drop_column('task_prep_prompt', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_prep_prompt', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task_prep_prompt', 'messages')
    op.add_column('flow_run', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
