"""Make adjustments to to model for syncing

Revision ID: 204ffefa2c93
Revises: c3af63c7368c
Create Date: 2024-02-23 19:55:29.722910

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = '204ffefa2c93'
down_revision = 'c3af63c7368c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('class_name', sa.String(), nullable=False))
    op.alter_column('integration', 'uses_api_key',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('short_name_unique_constraint', 'integration', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('short_name_unique_constraint', 'integration', type_='unique')
    op.alter_column('integration', 'uses_api_key',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('integration', 'class_name')
    # ### end Alembic commands ###
