"""Explicate nullablility for columns FlowRequest

Revision ID: 4575de758b88
Revises: 99ad46069d92
Create Date: 2023-07-13 10:38:21.148770

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = '4575de758b88'
down_revision = '99ad46069d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_request', 'request_instructions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_definition', 'parameters',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('task_operation', 'arguments',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_operation', 'arguments',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('task_definition', 'parameters',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('flow_request', 'request_instructions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
