"""Use Auth0 user model combined with self-managed one

Revision ID: 4d129cc23ac3
Revises: c5f6cb8b3ad0
Create Date: 2024-01-22 22:30:47.280285

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = '4d129cc23ac3'
down_revision = 'c5f6cb8b3ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth0_id', sa.String(), nullable=False))
    op.add_column('user', sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_user_auth0_id'), 'user', ['auth0_id'], unique=True)
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_auth0_id'), table_name='user')
    op.drop_column('user', 'permissions')
    op.drop_column('user', 'auth0_id')
    # ### end Alembic commands ###
