"""Adjust TaskDefinition for input fields

Revision ID: 7f9e3611ddb9
Revises: 204ffefa2c93
Create Date: 2024-02-23 22:32:14.210443

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = '7f9e3611ddb9'
down_revision = '204ffefa2c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
