"""Add datetime and ownership columns to execution tables

Revision ID: 889ebefe4b1c
Revises: 19a3279afd31
Create Date: 2024-03-26 11:15:55.554370

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = '889ebefe4b1c'
down_revision = '19a3279afd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('dependency', sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('flow_run', sa.Column('created_by_email', sa.String(), nullable=False))
    op.add_column('flow_run', sa.Column('modified_by_email', sa.String(), nullable=False))
    op.add_column('flow_run', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('flow_run', sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'flow_run', 'user', ['modified_by_email'], ['email'])
    op.create_foreign_key(None, 'flow_run', 'user', ['created_by_email'], ['email'])
    op.add_column('task_run', sa.Column('created_by_email', sa.String(), nullable=False))
    op.add_column('task_run', sa.Column('modified_by_email', sa.String(), nullable=False))
    op.add_column('task_run', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('task_run', sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'task_run', 'user', ['modified_by_email'], ['email'])
    op.create_foreign_key(None, 'task_run', 'user', ['created_by_email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_run', type_='foreignkey')
    op.drop_constraint(None, 'task_run', type_='foreignkey')
    op.drop_column('task_run', 'modified_date')
    op.drop_column('task_run', 'created_date')
    op.drop_column('task_run', 'modified_by_email')
    op.drop_column('task_run', 'created_by_email')
    op.drop_constraint(None, 'flow_run', type_='foreignkey')
    op.drop_constraint(None, 'flow_run', type_='foreignkey')
    op.drop_column('flow_run', 'modified_date')
    op.drop_column('flow_run', 'created_date')
    op.drop_column('flow_run', 'modified_by_email')
    op.drop_column('flow_run', 'created_by_email')
    op.drop_column('dependency', 'modified_date')
    op.drop_column('dependency', 'created_date')
    # ### end Alembic commands ###
