"""Add request_name to flow_request

Revision ID: 9c4682059501
Revises: 1e61ada14a13
Create Date: 2024-02-01 13:09:03.112574

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = '9c4682059501'
down_revision = '1e61ada14a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_request', sa.Column('request_name', sa.String(), nullable=True))
    op.add_column('task_definition', sa.Column('integration', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'task_definition', 'integration', ['integration'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_definition', type_='foreignkey')
    op.drop_column('task_definition', 'integration')
    op.drop_column('flow_request', 'request_name')
    # ### end Alembic commands ###
