"""Make adjustments to models for integration

Revision ID: c3af63c7368c
Revises: d4f5ef611a16
Create Date: 2024-02-22 20:06:35.423030

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = 'c3af63c7368c'
down_revision = 'd4f5ef611a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('sorted', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uix_integration_created_by', 'integration_credential', ['intergation', 'created_by_email'])
    op.create_unique_constraint('uix_integration_modified_by', 'integration_credential', ['intergation', 'modified_by_email'])
    op.drop_column('integration_credential', 'credential')
    op.add_column('task_definition', sa.Column('output_yml', sa.String(), nullable=False))
    op.drop_column('task_definition', 'parameters')
    op.drop_column('task_definition', 'python_code')
    op.add_column('task_operation', sa.Column('execution_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_operation', 'execution_position')
    op.add_column('task_definition', sa.Column('python_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('task_definition', sa.Column('parameters', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('task_definition', 'output_yml')
    op.add_column('integration_credential', sa.Column('credential', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_integration_modified_by', 'integration_credential', type_='unique')
    op.drop_constraint('uix_integration_created_by', 'integration_credential', type_='unique')
    op.drop_column('flow', 'sorted')
    # ### end Alembic commands ###
