"""Fix references between task op, dependency and flow

Revision ID: cb5891a5b371
Revises: e45eb1e8c65c
Create Date: 2024-03-01 16:40:36.592774

"""

from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = "cb5891a5b371"
down_revision = "e45eb1e8c65c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("task_operation", "index")
    op.add_column("task_operation", sa.Column("index", sa.INTEGER(), nullable=False))

    op.create_unique_constraint("_index_flow_uc", "task_operation", ["index", "flow"])

    op.drop_column("dependency", "source_task_operation")
    op.drop_column("dependency", "target_task_operation")

    # Recreate the columns with the new type
    op.add_column("dependency", sa.Column("source_task_operation", sa.Integer(), nullable=False))
    op.add_column("dependency", sa.Column("target_task_operation", sa.Integer(), nullable=False))

    op.create_unique_constraint(
        "_source_target_flow_uc", "dependency", ["source_task_operation", "target_task_operation", "flow"]
    )
    op.create_foreign_key(None, "dependency", "task_operation", ["target_task_operation", "flow"], ["index", "flow"])
    op.create_foreign_key(None, "dependency", "task_operation", ["source_task_operation", "flow"], ["index", "flow"])
    op.add_column("task_operation", sa.Column("sorted_index", sa.Integer(), nullable=True))
    op.drop_column("task_operation", "execution_position")
    op.drop_constraint("uix_task_run_answer", "task_prep_answer", type_="unique")
    op.create_unique_constraint("uix_task_run_and_answer", "task_prep_answer", ["task_run"])
    op.drop_constraint("uix_task_run_prompt", "task_prep_prompt", type_="unique")
    op.create_unique_constraint("uix_task_run_and_prompt", "task_prep_prompt", ["task_run"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_task_run", "task_prep_prompt", type_="unique")
    op.create_unique_constraint("uix_task_run_prompt", "task_prep_prompt", ["task_run"])
    op.drop_constraint("uix_task_run", "task_prep_answer", type_="unique")
    op.create_unique_constraint("uix_task_run_answer", "task_prep_answer", ["task_run"])
    op.add_column("task_operation", sa.Column("execution_position", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint("_index_flow_uc", "task_operation", type_="unique")
    op.alter_column("task_operation", "index", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("task_operation", "sorted_index")
    op.drop_constraint(None, "dependency", type_="foreignkey")
    op.drop_constraint(None, "dependency", type_="foreignkey")
    op.drop_constraint("_source_target_flow_uc", "dependency", type_="unique")
    # Drop the newly recreated columns
    op.drop_column("dependency", "source_task_operation")
    op.drop_column("dependency", "target_task_operation")

    # Recreate the original columns with UUID type
    op.add_column("dependency", sa.Column("source_task_operation", sa.UUID(as_uuid=True), nullable=False))
    op.add_column("dependency", sa.Column("target_task_operation", sa.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###
