"""Drop flow request body

Revision ID: d4f5ef611a16
Revises: 9c4682059501
Create Date: 2024-02-01 18:19:35.427882

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = 'd4f5ef611a16'
down_revision = '9c4682059501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_request', 'request_instructions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('flow_request', 'request_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_request', sa.Column('request_body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('flow_request', 'request_instructions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
