"""Make adjustments to task run models

Revision ID: e45eb1e8c65c
Revises: 7a7571858d19
Create Date: 2024-02-29 23:30:05.512777

"""

from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = "e45eb1e8c65c"
down_revision = "7a7571858d19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_operation", sa.Column("index", sa.Integer(), nullable=True))
    op.add_column("task_prep_answer", sa.Column("parameters", sa.JSON(), nullable=False))
    op.alter_column("task_prep_answer", "body", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint("uix_task_prep_prompt", "task_prep_answer", ["task_prep_prompt"])
    op.create_unique_constraint("uix_task_run_answer", "task_prep_answer", ["task_run"])
    op.drop_column("task_prep_answer", "has_python_execution")
    op.drop_column("task_prep_answer", "natural_language_explanation")
    op.create_unique_constraint("uix_task_run_prompt", "task_prep_prompt", ["task_run"])
    op.add_column("task_run", sa.Column("task_operation_index", sa.Integer(), nullable=False))
    op.drop_constraint("task_run_task_operation_fkey", "task_run", type_="foreignkey")
    op.drop_column("task_run", "arguments")
    op.drop_column("task_run", "task_operation")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_run", sa.Column("task_operation", sa.UUID(), autoincrement=False, nullable=False))
    op.add_column("task_run", sa.Column("arguments", sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key("task_run_task_operation_fkey", "task_run", "task_operation", ["task_operation"], ["id"])
    op.drop_column("task_run", "task_operation_index")
    op.drop_constraint("uix_task_run", "task_prep_prompt", type_="unique")
    op.add_column(
        "task_prep_answer", sa.Column("natural_language_explanation", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "task_prep_answer", sa.Column("has_python_execution", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("uix_task_run", "task_prep_answer", type_="unique")
    op.drop_constraint("uix_task_prep_prompt", "task_prep_answer", type_="unique")
    op.alter_column("task_prep_answer", "body", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("task_prep_answer", "parameters")
    op.drop_column("task_operation", "index")
    # ### end Alembic commands ###
