"""Remove output_name for task_def, add run models

Revision ID: fe414de8b9c7
Revises: da93eceb984d
Create Date: 2023-08-07 15:18:12.756168

"""
from alembic import op
import sqlalchemy as sa

import app.models.types

# revision identifiers, used by Alembic.
revision = 'fe414de8b9c7'
down_revision = 'da93eceb984d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_definition', 'output_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_definition', sa.Column('output_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
