default_context:
  project_name: 'Neena'
  project_slug: 'neena'
  domain_main: 'neena.io'
  domain_staging: 'stag.neena.io'
  domain_base_api_url: 'http://neena.io/api/v1'
  domain_base_ws_url: 'ws://neena.io/api/v1'
  docker_swarm_stack_name_main: 'neena-io'
  docker_swarm_stack_name_staging: 'stag-neena-io'
  secret_key: 'Land100!'
  first_superuser: 'admin@neena.io'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.neena.io", "https://stag.neena.io", "https://neena.io", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@neena.io'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@neena.io'
  postgres_password: 'Land100!'
  pgadmin_default_user: 'admin@neena.io'
  pgadmin_default_user_password: 'Land100!'
  neo4j_password: 'changethis'
  traefik_constraint_tag: 'neena.io'
  traefik_constraint_tag_staging: 'stag.neena.io'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
